[package]
name = "ansi_term_testing"
version = "0.1.0"
authors = ["Yuki Toyoda <yuki.multiplus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.11.0"